#!/bin/bash
set -x # show cmds
set -e # fail globally

####################################
echo Stage 1 - Building Dependencies
####################################


# install and update all apt-get dependencies
sudo apt autoremove
sudo apt-get update
sudo apt-get upgrade

pkgs="gcc g++ 
binutils-dev bison flex gawk autogen 
libgmp3-dev libmpc-dev 
libmpfr-dev libmpfr-doc libtool libtool-bin 
check dejagnu expect 
mpc flex gettext libisl23 libisl-dev libtool patch gperf 
texinfo libcloog-isl-dev 
build-essential glibc-devel ia32-libs 
gcc-multilib g++-multilib libc6-i386 grub2-common grub-pc 
guile-3.0 guile-3.0-dev guile-3.0-libs guile-3.0-doc 
xorriso mtools grub-pc-bin qemu-system-i386 bochs bochs-x bochsbios vgabios nasm 
build-essential flex bison libgmp-dev libmpfr-dev libmpc-dev zlib1g-dev texinfo
libgmp-dev libmpfr-dev libmpc-dev zlib1g-dev lib32stdc++6 lib32z1 lib32ncurses6 libcupsimage2:i386
"
for pkg in $pkgs; do
  (sudo apt-get -y --ignore-missing install $pkg || true)
done

date +%T >> $1
echo "[setup-gcc : exit]\n" >> $1



